### ISSUE TITLE
GCP上面运行遇到错误option == is not support

### ISSUE THREAD

**Issue by liuygem** [BennyThink/ServerSan#1]
--2018-03-30 05:49:14--  https://raw.githubusercontent.com/BennyThink/ServerSan/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3514 (3.4K) [text/plain]
Saving to: ‘install.sh.3’

install.sh.3                 100%[===========================================>]   3.43K  --.-KB/s    in 0s      

2018-03-30 05:49:14 (77.6 MB/s) - ‘install.sh.3’ saved [3514/3514]

Current OS: Ubuntu 17.10
Current Options: AgVmQFJVYuOZs7EvTWVEgA==
option AgVmQFJVYuOZs7EvTWVEgA== is not support

**Comment by BennyThink** [comment]
我没能复现这个问题，你使用的安装命令是这个吗（root权限）？
```bash
wget  https://raw.githubusercontent.com/BennyThink/ServerSan/master/install.sh && bash install.sh AgVmQFJVYuOZs7EvTWVEgA==
```
，建议先尝试删除当前目录下的install.sh，重新在bot里选择add试试？

**Comment by liuygem** [comment]
Execute the following command(unused server will be deleted within 30 minutes):

wget https://raw.githubusercontent.com/BennyThink/ServerSan/master/install.sh&& bash install.sh AgVmQFJVYuOZs7EvTWVEgA==

bot发送的这个，然后我用root用户运行

**Comment by BennyThink** [comment]
@liuygem 
我在虚拟机上试了下，似乎是没有问题的。直接运行
`bash install.sh AgVmQFJVYuOZs7EvTWVEgA==`是否可以？（注意文件名）

**Comment by liuygem** [comment]
OK了，抱歉，是存在同名文件
